; Une configuration générique pour une seule base de données.

[alembic]
; Modèle utilisé pour générer les fichiers de migration.
; file_template = %%(rev)s_%%(slug)s
; Défini à 'true' pour exécuter l'environnement pendant la commande 'revision', indépendamment de l'autogénération.
; revision_environment = false

; Répertoire où les versions de migration sont stockées.
version_locations = %(here)s/versions

; La section [loggers] définit les loggers utilisés dans l'application.
; Spécifie les loggers à utiliser, dans ce cas, 'root', 'sqlalchemy', et 'alembic'.
[loggers]
keys = root,sqlalchemy,alembic

; La section [handlers] définit les gestionnaires de journalisation.
; 'keys' spécifie les gestionnaires à utiliser, dans ce cas, 'console'.
[handlers]
keys = console

; La section [formatters] définit les formateurs de journalisation.
; 'keys' spécifie les formateurs à utiliser, dans ce cas, 'generic'.
[formatters]
keys = generic

; Configure le logger racine.
; Niveau de journalisation pour le logger racine.
; Gestionnaires à utiliser pour le logger racine.
; Qualname pour le logger racine.
[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

; Définit le gestionnaire de journalisation 'console'.
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

; Définit le formateur de journalisation 'generic'.
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
